### ISSUE TITLE
Standardize Error Formats

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/cadasta-api#1]
Parameter and Option errors seems to have a standard format and at least has a hash key of `message` as seen in [error.js](https://github.com/Cadasta/cadasta-api/blob/master/app/errors.js#L3-L15z)

If something bad goes wrong in some calls, such as [create one project](https://github.com/Cadasta/cadasta-api/blob/dev/app/routes/projects.js#L242), we return an error hash without a `message` hash key.

Let's make sure `500(s)` dump errors with a standard format too.

**Comment by hallahan** [comment]
:+1

**Comment by rgwozdz** [comment]
This is the error handling middleware:https://github.com/Cadasta/cadasta-api/issues/1

**Comment by thebigspoon** [comment]
@rgwozdz,
Thanks, the middleware already did what I wanted it to do. We just had to return the full error. minor cleanup
